language: java
sudo: false
cache:
  directories:
  - $HOME/.m2
install: mvn compile -DskipTests=true -Dmaven.javadoc.skip=true -Djacoco.skip=true -B -V
before_script: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: mvn install -B -V
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mvn site --settings target/travis/settings.xml -B -V
branches:
  except:
    - travis
    - gh-pages
env:
  global:
    - secure: "h9NfI5aFT1H1UyZCj0u/Cbt0q1167OtTyGXo0AbE6lPxpttOkoFi0FkIvs/pppsXZGN6xp0pWKIMrcfMsK12nW8NH9r/hBekgVXYaJPmpnNSCephkgMoPNJFU5AByyWJo9qm5FFYlTEEwJS/1ZD9dREfbaTEgAN2tzBAjciC0PA="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1eb7b5d84ad8b708b093
    on_success: change
    on_failure: always
    on_start: false

